[project]
name = "rl-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.30.1",
    "marimo>=0.15.0",
    "numpy>=2.3.2",
    "torch==2.7.1",
]

[tool.uv.workspace]
members = [
    "PPO",
]
