[project]
name = "ppo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gym==0.22",
    "huggingface-hub>=0.34.4",
    "imageio-ffmpeg>=0.6.0",
    "pyglet>=2.1.8",
    "pyvirtualdisplay>=3.0",
]
